Fix issue with missing repository name for
-Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.defaultImage

Error was:
ERROR: Unable to pull Docker image "basic-agent:3.35".
Check if image tag name is spelled correctly.